<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Rinha.FraudDetection.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rinha.FraudDetection.Application\Rinha.FraudDetection.Application.csproj" />
    <ProjectReference Include="..\Rinha.FraudDetection.Domain\Rinha.FraudDetection.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>
</Project>
